#!/usr/bin/perl
use FindBin '$Bin';
use feature 'say';


@ports = split ',', $ENV{NAMES_PORTS};
@names = split ',', $ENV{DUCKDNS_NAMES};

!@names and die "No ENV DUCKDNS_NAMES: ".$ENV{NAMES_PORTS};
@ports != @names and die "miscount NAMES_PORTS <-> DUCKDNS_NAMES";

# In tunnel mode, ssh-tunnel-source reverse-forwards the jump server's
#   ports 80/443 back to Caddy here. 'jamsend-fe' is resolved via the
#   ssh_config file generated by install.sh (there/ssh_config).
$tunnel_mode = ($ENV{TUNNEL_MODE} // '') eq 'true';

open $fh, '>', "$Bin/docker-compose.yml";
print $fh <<'';
services:
  # tells duckdns your ip
  duckdns-updater:
    build:
      context: .
      dockerfile_inline: |
        FROM alpine:3.19
        RUN apk add --no-cache curl
        COPY duckdns_update.sh /
        CMD ["ash","duckdns_update.sh"]
    environment:
      - PUBLIC_IP=${PUBLIC_IP}
      - DUCKDNS_NAMES=${DUCKDNS_NAMES}
      - DUCKDNS_TOKEN=${DUCKDNS_TOKEN}
    # dont leave a failing update loop going
    restart: no


if ($tunnel_mode) {
    print $fh <<'';
  # ssh -R connects the jump server's :80 and :443 to the Caddy service here.
  # 'jamsend-fe' is resolved via /root/.ssh/config (mounted from ssh_config below).
  ssh-tunnel-source:
    build:
      context: .
      dockerfile_inline: |
        FROM alpine:3.19
        RUN apk add --no-cache openssh-client
        RUN mkdir -p /root/.ssh && chmod 700 /root/.ssh
    command: |
        sh -c '
          echo "$$SSH_PRIVATE_KEY" > /root/.ssh/id_ed25519 && \
          chmod 600 /root/.ssh/id_ed25519 && \
          cp /ssh_config /root/.ssh/config && \
          ssh -i /root/.ssh/id_ed25519 jamsend-fe "
            # reap orphaned sshd sessions holding our forward ports.
            # PID 1 is the listener; \$$PPID is the sshd serving this very session.
            for p in \$$(pidof sshd); do
              case \"\$$p\" in 1|\$$PPID) ;; *) kill \"\$$p\" 2>/dev/null ;; esac
            done
            sleep 1
          " || true; \
          exec ssh -v -N \
            -o ExitOnForwardFailure=yes \
            -o ServerAliveInterval=15 \
            -o ServerAliveCountMax=3 \
            -R 0.0.0.0:80:caddy:80 \
            -R 0.0.0.0:443:caddy:443 \
            -R 0.0.0.0:9999:caddy:443 \
            -i /root/.ssh/id_ed25519 \
            jamsend-fe'
    environment:
      - SSH_PRIVATE_KEY=${SSH_PRIVATE_KEY}
    configs:
      - source: ssh_config
        target: /ssh_config
    depends_on:
      - caddy
    networks:
      - web
    restart: always

}

print $fh <<'';
  # this caddy uses DNS challenges (duckdns plugin) — no port 80 needed for cert issuance
  caddy:
    build:
      context: .
      dockerfile_inline: |
        FROM caddy:2-builder AS builder
        RUN xcaddy build --with github.com/caddy-dns/duckdns
        FROM caddy:2
        COPY --from=builder /usr/bin/caddy /usr/bin/caddy
    environment:
      - DUCKDNS_TOKEN=${DUCKDNS_TOKEN}
    ports:
      - ":80"
      - ":443"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - ./logs:/var/log/caddy
    configs:
      - source: caddy_config
        target: /etc/caddy/Caddyfile
    networks:
      - web
    restart: always
  
volumes:
  caddy_data:
  caddy_config:
networks:
  web:
configs:


# In tunnel mode, also add the ssh_config Docker config so ssh-tunnel-source
#   can mount the Host→IP mapping without baking PUBLIC_IP into the image.
if ($tunnel_mode) {
    print $fh <<'';
  ssh_config:
    file: ./there/ssh_config

}

print $fh <<'';
  caddy_config:
    content: |


# all dockers on your machine can bind ports on the docker0 interface
#  which is usually at this ip
$docker0ip = '172.17.0.1';
 
# could include 192.168.0.0/16 here 
#  to allow /log from other hosts on the LAN
$local_includes = '192.168.0.0/16';

# < $docker0ip should be derived from `ip addr | grep docker0`
for $name (@names) {
    ($port,$host) = reverse split ':', shift @ports;
    $host ||= $docker0ip;
    say " - handle $name -> $host:$port";
    $host !~ /^[\w\.:]+$/ and die "weird host: $host";
    $port !~ /^\d+$/       and die "weird port: $port";

    $extra = "";
    if ($name =~ /^d?(jam|vou)/) {
        # these are extra ports we forward everything under a path (without the path) to
        # share a WebRTC signaling server aft Caddy
        # handle_path implicitly strips the prefix. If you visit example.com/log, 
        #  Caddy sends / to the Mojo server
        $extra .= <<"";
          handle_path /peerjs-server/* {
              reverse_proxy $host:9995
          }
          handle_path /log {
              #\@not_local not remote_ip 127.0.0.1 10.0.0.0/8 172.16.0.0/12 $local_includes
              #abort \@not_local
              reverse_proxy $host:9393 {
                header_up Host {host}
                header_up X-Real-IP {remote_host}
              }
          }

    }

    print $fh <<""
      $name.duckdns.org {
          encode zstd gzip
          tls {
              dns duckdns {env.DUCKDNS_TOKEN}
          }

    . $extra
    . <<"";
          handle {
              reverse_proxy $host:$port
          }
          header {
              Strict-Transport-Security "max-age=31536000; includeSubDomains; preload"
              X-Content-Type-Options "nosniff"
              X-XSS-Protection "1; mode=block"
              X-Frame-Options "DENY"
          }
          log {
              output file /var/log/caddy/$name/access.log
              format console
          }
      }
      http://$name.duckdns.org {
          redir https://{host}{uri} permanent
      }

}

close STDOUT;
say "done";
